<?php
session_start();
include('../config/db.php');

// 📌 manual Dompdf (NO composer)
require_once '../dompdf/autoload.inc.php';

use Dompdf\Dompdf;

$dompdf = new Dompdf();

// 📦 Get stock
$stock = mysqli_query($conn,"
  SELECT i.name, s.quantity
  FROM stock s
  JOIN ingredients i ON i.id = s.ingredient_id
");

$html = "
<h2 style='text-align:center;'>☕ Le Chic Café</h2>
<h3 style='text-align:center;'>Closing Stock Report</h3>
<p style='text-align:center;'>Generated: " . date("Y-m-d H:i:s") . "</p>

<hr>

<table width='100%' border='1' cellpadding='8' cellspacing='0'>
<tr style='background:#f2f2f2;'>
  <th>Ingredient</th>
  <th>Quantity</th>
</tr>
";

while($s = mysqli_fetch_assoc($stock)){
  $html .= "
  <tr>
    <td>{$s['name']}</td>
    <td>{$s['quantity']}</td>
  </tr>
  ";
}

$html .= "</table>

<br><br>
<p style='text-align:center; font-size:12px;'>
Generated by Le Chic Café System
</p>
";

// 📄 Load HTML
$dompdf->loadHtml($html);

// 📄 Paper settings
$dompdf->setPaper('A4', 'portrait');

// 🚀 Render PDF
$dompdf->render();

// 📥 Download
$dompdf->stream("closing_stock_" . date("Ymd_His") . ".pdf", ["Attachment" => true]);
?>